sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-ap-northeast-1.aliyuncs.com
    access-key-id: LTAI5tFThytojD2EqrekhbvB
    access-key-secret: 3Hbj6B8m1lDoDsfdVhgCGqK3bhN9dF
    bucket-name: sky-itcast-gjx
